let products = [
	{id:1,name:'Arlo lounge chair',category:'Seating',price:680,image:'',description:''},
	{id:2,name:'Noma dining table',category:'Tables',price:1240,image:'',description:''},
	{id:3,name:'Lune pendant light',category:'Bedrooms',price:290,image:'',description:''},
	{id:4,name:'Cove modular sofa',category:'Seating',price:2180,image:'',description:''},
	{id:5,name:'Milo side table',category:'Tables',price:340,image:'',description:''},
	{id:6,name:'Sora floor lamp',category:'Bedrooms',price:410,image:'',description:''},
	{id:7,name:'Etta dining chair',category:'Seating',price:390,image:'',description:''},
	{id:8,name:'Pietro coffee table',category:'Tables',price:890,image:'',description:''},
	{id:9,name:'Mori table lamp',category:'Bedrooms',price:245,image:'',description:''},
	{id:10,name:'Haven daybed',category:'Seating',price:1560,image:'',description:''},
	{id:11,name:'Alba console',category:'Tables',price:760,image:'',description:''},
	{id:12,name:'Orb wall light',category:'Bedrooms',price:180,image:'',description:''}
];
const savedProducts=JSON.parse(localStorage.getItem('furnshop-products')||'[]').slice(-4).map(product=>({...product,category:product.category==='Lighting'?'Bedrooms':product.category}));
const removedProductIds=JSON.parse(localStorage.getItem('furnshop-removed-products')||'[]');
products=[...products,...savedProducts].filter(product=>!removedProductIds.includes(product.id));
let activeFilter='All';
let searchTerm='';
let cart=JSON.parse(localStorage.getItem('hearth-cart')||'[]');
let favorites=JSON.parse(localStorage.getItem('hearth-favorites')||'[]');
const $=selector=>document.querySelector(selector);
const money=value=>`Tsh ${value.toLocaleString('en-US')}`;
function save(){try{localStorage.setItem('hearth-cart',JSON.stringify(cart));}catch(error){console.warn('Cart could not be saved.',error);}try{localStorage.setItem('hearth-favorites',JSON.stringify(favorites));}catch(error){console.warn('Favorites could not be saved.',error);}}
function saveCatalog(){try{localStorage.setItem('furnshop-products',JSON.stringify(products.filter(product=>product.id>12)));localStorage.setItem('furnshop-removed-products',JSON.stringify(removedProductIds));}catch(error){console.warn('Catalog could not be saved.',error);}}
function filteredProducts(){let list=products.filter(p=>p.image&&(activeFilter==='All'||p.category===activeFilter)&&(p.name.toLowerCase().includes(searchTerm.toLowerCase())||p.category.toLowerCase().includes(searchTerm.toLowerCase())));const sort=$('#sort-select').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);return list;}
function renderProducts(){const list=filteredProducts();$('#product-total').textContent=`${list.length} ${list.length===1?'piece':'pieces'}`;$('#empty-state').hidden=list.length>0;$('#product-grid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" data-product="${p.id}">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:''}<button class="favorite ${favorites.includes(p.id)?'active':''}" aria-label="${favorites.includes(p.id)?'Remove from':'Add to'} favorites" data-favorite="${p.id}">${favorites.includes(p.id)?'♥':'♡'}</button></div><h3>${p.name}</h3><div class="product-meta"><span>${p.category}</span><strong>${money(p.price)}</strong></div></article>`).join('');}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.quantity,0);$('#cart-count').textContent=count;$('#cart-total').textContent=money(cart.reduce((sum,item)=>sum+item.price*item.quantity,0));$('#cart-items').innerHTML=cart.length?cart.map(item=>`<div class="cart-row"><img src="${item.image}" alt="${item.name}"><div><h4>${item.name}</h4><p>${item.quantity} x ${money(item.price)}</p><button class="remove-item" data-remove="${item.id}">Remove</button></div><span class="cart-price">${money(item.price*item.quantity)}</span></div>`).join(''):'<div class="empty-cart">Your bag is waiting for something good.</div>';}
function renderCheckout(){const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);$('#checkout-total').textContent=money(total);}
function openCart(){renderCart();$('#cart-drawer').classList.add('open');$('#drawer-scrim').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false');}
function closeCart(){$('#cart-drawer').classList.remove('open');$('#drawer-scrim').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true');}
function addToCart(product){if(!product)return;const existing=cart.find(item=>item.id===product.id);if(existing)existing.quantity++;else cart.push({...product,quantity:1});products=products.filter(item=>item.id!==product.id);if(!removedProductIds.includes(product.id))removedProductIds.push(product.id);save();saveCatalog();renderProducts();renderCart();showToast(`${product.name} added to your bag`);}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400);}
function renderAdminProducts(){$('#admin-products-list').innerHTML=products.filter(product=>product.image).map(product=>`<div class="admin-product-row"><img src="${product.image}" alt="${product.name}"><span>${product.name}</span><button type="button" data-delete-product="${product.id}">Delete</button></div>`).join('')||'<p class="admin-empty">No uploaded products yet.</p>';}
function openAdmin(){renderAdminProducts();$('#admin-modal').hidden=false;}
function closeAdmin(){$('#admin-modal').hidden=true;}
function resetImagePreview(){$('#product-image').value='';$('#upload-file-name').textContent='No image selected';$('#image-preview').hidden=true;$('#image-preview-img').removeAttribute('src');}
function readImage(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('File read failed'));reader.readAsDataURL(file);});}
function openProduct(id){const p=products.find(product=>product.id===id);const image=p.image?`<img src="${p.image}" alt="${p.name}">`:'';$('#modal-content').innerHTML=`<div class="modal-product">${image}<div><p class="eyebrow">${p.category}</p><h2>${p.name}</h2><p>${p.description}</p><div class="modal-price">${money(p.price)}</div><button class="button button-dark" data-add="${p.id}">Add to bag <span>-></span></button><button class="back-to-products" data-action="close-modal">← Back to products</button></div></div>`;$('#product-modal').hidden=false;}
document.addEventListener('click',event=>{const target=event.target.closest('button,a,img');if(!target)return;if(target.dataset.filter){activeFilter=target.dataset.filter;document.querySelectorAll('[data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===activeFilter));renderProducts();return;}if(target.dataset.filterLink){activeFilter=target.dataset.filterLink;document.querySelectorAll('[data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===activeFilter));renderProducts();return;}if(target.dataset.favorite){const id=Number(target.dataset.favorite);favorites=favorites.includes(id)?favorites.filter(item=>item!==id):[...favorites,id];save();renderProducts();return;}if(target.dataset.product){openProduct(Number(target.dataset.product));return;}if(target.dataset.add){addToCart(products.find(p=>p.id===Number(target.dataset.add)));$('#product-modal').hidden=true;return;}if(target.dataset.remove){cart=cart.filter(item=>item.id!==Number(target.dataset.remove));save();renderCart();return;}if(target.dataset.deleteProduct){const id=Number(target.dataset.deleteProduct);products=products.filter(product=>product.id!==id);if(!removedProductIds.includes(id))removedProductIds.push(id);saveCatalog();renderProducts();renderAdminProducts();return;}const action=target.dataset.action;if(action==='admin')openAdmin();if(action==='close-admin')closeAdmin();if(action==='remove-image')resetImagePreview();if(action==='cart')openCart();if(action==='close-cart')closeCart();if(action==='close-modal')$('#product-modal').hidden=true;if(action==='menu')document.querySelector('.main-nav').classList.toggle('mobile-open');if(action==='back-cart'){$('#checkout-panel').hidden=true;$('#cart-items').hidden=false;$('.cart-footer').hidden=false;$('.drawer-header').hidden=false;}});
$('#product-image').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;if(!file.type.startsWith('image/')){showToast('Please choose an image file');resetImagePreview();return;}if(file.size>5*1024*1024){showToast('Please choose an image under 5MB');resetImagePreview();return;}$('#upload-file-name').textContent=file.name;const reader=new FileReader();reader.onload=()=>{$('#image-preview-img').src=reader.result;$('#image-preview').hidden=false;};reader.onerror=()=>showToast('Image could not be loaded');reader.readAsDataURL(file);});
$('#product-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const formData=new FormData(form);const imageFile=formData.get('image');if(!form.elements.name.value.trim()||!form.elements.category.value||!form.elements.price.value||!form.elements.description.value.trim()){showToast('Complete all product details');return;}if(!imageFile||!imageFile.size){showToast('Please add a product image');return;}readImage(imageFile).then(image=>{const product={id:Date.now(),name:formData.get('name').trim(),category:formData.get('category'),price:Number(formData.get('price')),image,description:formData.get('description').trim()};products.push(product);renderProducts();try{localStorage.setItem('furnshop-products',JSON.stringify(products.filter(item=>item.id>12)));}catch(error){console.warn('Product saved for this session only because browser storage is full.');}form.reset();resetImagePreview();renderAdminProducts();closeAdmin();alert('Product uploaded successfully!');}).catch(error=>{console.warn('Product image could not be read.',error);showToast('Image could not be loaded');});});
$('#sort-select').addEventListener('change',renderProducts);document.addEventListener('keydown',event=>{if(event.key==='Escape'){$('#product-modal').hidden=true;closeCart();}});renderProducts();renderCart();
